functional wiring including ibeacon checks but not ibeacon data

diff --git a/kitsune b/kitsune
--- a/kitsune
+++ b/kitsune
@@ -1,40 +1,145 @@
-#!/bin/sh
+#!/bin/sh -x
 
 NAME=kitsune
 LOGFILE="/var/log/${NAME}.log"
 
-bluetooth() {
+bluetooth_checks() {
+  #make sure BLUETOOTH_DEV exists
+  if [ -n "${BLUETOOTH_DEV}" ] && hciconfig "${BLUETOOTH_DEV}" > /dev/null 2>&1; then
+    printf "BLUETOOTH_DEV \"%s\" exists, continuing.\n" "${BLUETOOTH_DEV}"
+  else
+    printf "FATAL BLUETOOTH_DEV \"%s\" does not exist.\n" "${BLUETOOTH_DEV}"
+    exit
+  fi
+  #unblock
+  printf "Bluetooth device found, unblocking rfkill...\n"
+  if rfkill unblock bluetooth; then
+    printf "Bluetooth unblocked.\n"
+  else
+    printf "Bluetooth rfkill is stuck.\n"
+    exit 1
+  fi
+  #make sure interface is running
+  printf "Bluetooth starting...\n"
+  if hciconfig "${BLUETOOTH_DEV}" up; then
+    printf "Bluetooth is running.\n"
+  else
+    printf "FATAL Failed to start bluetooth.\n"
+  fi
+}
+
+ibeacon_checks() {
+  if [ -z "${IBEACON_PROX_UUID}" ] || [ "${#IBEACON_PROX_UUID}" != 16 ]; then
+    printf "FATAL IBEACON_PROX_UUID must be 16 hex characters\n"
+    exit 1
+  fi
+  if echo "${IBEACON_PROX_UUID}" | grep -qiE --color=never '[a-f0-9]{16}'; then
+    true
+  else
+    printf "FATAL IBEACON_PROX_UUID must be hex\n."
+    exit 1
+  fi
+  if [ -z "${IBEACON_MAJOR}" ] || [ "${#IBEACON_MAJOR}" != 4 ] || [ -z "${IBEACON_MINOR}" ] || [ "${#IBEACON_MINOR}" != 4 ]; then
+    printf "FATAL IBEACON_MAJOR and IBEACON_MINOR must be 4 hex characters\n"
+    exit 1
+  fi
+  if echo "${IBEACON_MAJOR}" | grep -qiE --color=never '[a-f0-9]{4}'; then
+    printf "FATAL IBEACON_MAJOR must be hex\n"
+    exit 1
+  fi
+  if echo "${IBEACON_MINOR}" | grep -qiE --color=never '[a-f0-9]{4}'; then
+    printf "FATAL IBEACON_MINOR must be hex\n"
+    exit 1
+  fi
+  if [ -z "${IBEACON_RSSI}" ] || [ "${#IBEACON_RSSI}" != 2 ]; then
+    printf "FATAL IBEACON_RSSI must be 2 hex characters\n"
+    exit 1
+  fi
+  if echo "${IBEACON_RSSI}" | grep -qiE --color=never '[a-f0-9]{2}'; then
+    true
+  else
+    printf "FATAL IBEACON_RSSI must be hex\n."
+    exit 1
+  fi
+  if [ -z "${IBEACON_INTERVAL_MS}" ]; then
+    printf "FATAL IBEACON_INTERVAL_MS must be set.\n"
+    exit 1
+  fi
+  if [ "${IBEACON_INTERVAL_MS}" -lt 100 ] || [ $(echo "${IBEACON_INTERVAL_MS} > 40959.375" | bc -l) -eq 1 ]; then
+    printf "FATAL IBEACON_INTERVAL_MS must be between 100 and 40,959.375.\n"
+    exit 1
+  fi
+}
+
+kitsune_bluetooth() {
   case "${1}" in
     start)
+      bluetooth_checks
+      #set mac if requested
+      if [ -n "${BLUETOOTH_MAC}" ]; then
+        if echo "${BLUETOOTH_MAC}" | grep -qE '([[:xdigit:]]{2}:){5}[[:xdigit:]]{2}'; then
+          bdaddr -i "${BLUETOOTH_DEV}" -r "${BLUETOOTH_MAC}"
+        else
+          printf "BLUETOOTH_MAC \"%s\" doesn\'t appear to be a valid mac address.  Ignoring.\n" "${BLUETOOTH_MAC}" 2>&1
+        fi
+      fi
+      #set name if requested
+      if [ -n "${BLUETOOTH_NAME}" ]; then
+        if [ "${#BLUETOOTH_NAME}" -gt 48 ]; then
+          printf "BLUETOOTH_NAME is longer than 48 characters and will be truncated.\n"
+        fi
+        hciconfig "${BLUETOOTH_DEV}" name "${BLUETOOTH_NAME}"
+      fi
+      #base config in place, reset to make it effective
+      hciconfig "${BLUETOOTH_DEV}" reset
+      #pscan is enabled on reset and we don't want to be pairable
+      hciconfig "${BLUETOOTH_DEV}" noscan
+      #bluetooth classic came first
+      if [ -n "${CLASSIC_DISCOVERABLE}" ] && [ "${CLASSIC_DISCOVERABLE}" = "true" ]; then
+        hciconfig "${BLUETOOTH_DEV}" iscan
+      fi
+      #iBeacon
+      if [ -n "${IBEACON_ENABLED}" ] && [ "${IBEACON_ENABLED}" = "true" ]; then
+        ibeacon_checks
+      fi
       ;;
     stop)
-      hciconfig "${bluetooth}" noscan
+      hciconfig "${BLUETOOTH_DEV}" noscan
+      hciconfig "${BLUETOOTH_DEV}" noleadv
+      hciconfig "${BLUETOOTH_DEV}" reset
+      rfkill block all
       ;;
     *)
       printf "FATAL: bluetooth function called without start or stop.\n"
       ;;
+  esac
 }
 
 main() {
   case "${1}" in
     start)
-      printf "[+] Starting %s...\n" "${NAME}"
+      printf "[+] Starting Kitsune FaaS...\n"
 
       #first, shut up
       rfkill block all
 
-      printf "[+] %s completed.\n" "${NAME}"
+      if [ "${BLUETOOTH_ENABLED}" = "true" ]; then
+        kitsune_bluetooth start
+      fi
+
+      printf "[+] Kitsune FaaS completed.\n"
       exit 0
       ;;
     stop)
-      printf "[+] Stopping %s...\n" "${NAME}"
+      printf "[+] Stopping Kitsune FaaS...\n"
 
       #quiet, we are shutting down
       rfkill block all
 
       #it might be a restart, so shut everything down
+      kitsune_bluetooth stop
 
-      printf "[+] %s stopped.\n" "${NAME}"
+      printf "[+] Kitsune FaaS stopped.\n"
       exit 0
       ;;
 
